repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4  # or latest stable release
    hooks:
      - id: ruff-check
        args: [--fix]


  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.4
    hooks:
      - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: .pre-commit-config.yaml
      - id: check-json
      - id: debug-statements
